#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# A null crawler, for testing crawler.py

# I m p o r t s

import os, sys
from crawler import Crawler

# V a r i a b l e s

MYNAME = os.path.basename(sys.argv[0])

# C l a s s e s

class NullCrawler(Crawler):
    def visit(self, url, raw, parsed):
        print("[Visited " + repr(url) + ".]")

    def message(self, level, text):
        sys.stderr.write("{0}: {1} - {2}\n".format(MYNAME, level, text))


# M a i n   P r o g r a m

crawler = NullCrawler(sys.argv[2:], domain=sys.argv[1])
crawler.crawl()
